
"""
Problem:
You are given two strings s and t which consist of only lowercase letters. String t is generated by random shuffling string s and then adding one more letter at a random position. Find the letter that was added in t.
Example:
Input: s = "abcd", t = "abcde"
Output: "e"
"""



def findTheDifference(s: str, t: str) -> str:
    # Initialize a variable to store the XOR result
    result = 0
    
    # XOR all characters of string s
    for char in s:
        result ^= ord(char)
    
    # XOR all characters of string t
    for char in t:
        result ^= ord(char)
    
    # The remaining value in result will be the added character
    return chr(result)